apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  type: NodePort
  selector:
    app: kubernetes-bootcamp  # TO COMPLETE
  ports:
    - port: 8080 # TO COMPLETE
      targetPort: 8080
      nodePort: 30008